In [323]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

# if response code is 403
 - headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
 -requests.get('url',headers=headers).text

In [324]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage= requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

In [325]:
webpage

'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ambitionbox&#46;com&#47;list&#45;of&#45;companies&#63;" on this server.<P>\nReference&#32;&#35;18&#46;d1cc517&#46;1783250141&#46;c08b2728\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;d1cc517&#46;1783250141&#46;c08b2728</P>\n</BODY>\n</HTML>\n'

In [326]:
soup=BeautifulSoup(webpage,'lxml')   
# soup = BeautifulSoup(webpage,'lxml')

In [327]:
print(soup.prettify())

<html>
 <head>
  <title>
   Access Denied
  </title>
 </head>
 <body>
  <h1>
   Access Denied
  </h1>
  You don't have permission to access "http://www.ambitionbox.com/list-of-companies?" on this server.
  <p>
   Reference #18.d1cc517.1783250141.c08b2728
  </p>
  <p>
   https://errors.edgesuite.net/18.d1cc517.1783250141.c08b2728
  </p>
 </body>
</html>

In [328]:
soup.find_all('h1')[0].text

'Access Denied'

In [329]:
" ".join(soup.find_all('h1')[0].text.split())

'Access Denied'

# TO FIND OUT NAMES OF THE COMPANIES

In [330]:

for i in soup.find_all('h2'):
  print(i.text.strip())

In [331]:
for i in soup.find_all('p'):
  print(i.text.strip())

Reference #18.d1cc517.1783250141.c08b2728
https://errors.edgesuite.net/18.d1cc517.1783250141.c08b2728

## TO FIND OUT THE RATINGS

In [332]:
soup.find_all('p')

[<p>
 Reference #18.d1cc517.1783250141.c08b2728
 </p>,
 <p>https://errors.edgesuite.net/18.d1cc517.1783250141.c08b2728</p>]

In [333]:
soup.find_all(class_='rating_text rating_text--md')

[]

## TO FIND OUT THE NUMBER OF REVIEWS

In [334]:
len(soup.find_all(class_='companyCardWrapper__companyRatingCount'))

0

# CONSIDERING THE WHOLE CONTAINER

In [335]:
company=soup.find_all(class_='companyCardWrapper')
# company

In [336]:
len(company)

0

In [337]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]


for i in company:

  name.append(i.find('h2').text.strip())
  rating.append(i.find(class_='rating_text').text.strip())
  reviews.append(i.find(class_='companyCardWrapper__companyRatingCount').text.strip())
  ctype.append(i.find_all(class_='companyCardWrapper__interLinking')[0].text.strip().split('|')[0].strip())
  hq.append(i.find_all(class_='companyCardWrapper__interLinking')[0].text.strip().split('|')[1].strip())


df=pd.DataFrame({'name':name,
   'rating':rating,
   'reviews':reviews,
   'company_type':ctype,
   'Head_Quarters':hq,
   })

In [338]:
df

Empty DataFrame
Columns: [name, rating, reviews, company_type, Head_Quarters]
Index: []

In [339]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]


for i in company:

  try:
    name.append(i.find('h2').text.strip())
  except:
    name.append(np.nan)
  
  try:
    rating.append(i.find(class_='rating_text').text.strip())
  except:
    rating.append(np.nan)
  
  try:
    reviews.append(i.find(class_='companyCardWrapper__companyRatingCount').text.strip())
  except:
    reviews.append(np.nan)
  
  try:
    ctype.append(i.find_all(class_='companyCardWrapper__interLinking')[0].text.strip().split('|')[0].strip())
  except:
    ctype.append(np.nan)
  
  try:
    hq.append(i.find_all(class_='companyCardWrapper__interLinking')[0].text.strip().split('|')[1].strip())
  except:
    hq.append(np.nan)
  
  


df=pd.DataFrame({'name':name,
   'rating':rating,
   'reviews':reviews,
   'company_type':ctype,
   'Head_Quarters':hq,
   })

In [340]:
df

Empty DataFrame
Columns: [name, rating, reviews, company_type, Head_Quarters]
Index: []

In [341]:
name

[]

# creating dataframe for all the pages

In [342]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage= requests.get('https://www.ambitionbox.com/list-of-companies?page={}',headers=headers).text

In [352]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
}

final = pd.DataFrame()

for j in range(1, 91):

    # FIX 1: headers pass karo
    webpage = requests.get(
        f"https://www.ambitionbox.com/list-of-companies?page={j}",
        headers=headers
    ).text

    soup = BeautifulSoup(webpage, "lxml")

    # FIX 2: new class name
    company = soup.find_all(class_="companyCardWrapper")

    name = []
    rating = []
    reviews = []
    ctype = []
    hq = []

    for i in company:

        try:
            name.append(i.find("h2").text.strip())
        except:
            name.append(np.nan)

        try:
            # FIX 3: rating_text
            rating.append(i.find(class_="rating_text").text.strip())
        except:
            rating.append(np.nan)

        try:
            # FIX 4: new review class
            reviews.append(i.find(class_="companyCardWrapper__companyRatingCount").text.strip())
        except:
            reviews.append(np.nan)

        try:
            # FIX 5: split first interLinking element
            info = i.find_all(class_="companyCardWrapper__interLinking")[0].text.strip().split("|")
            ctype.append(info[0].strip())
        except:
            ctype.append(np.nan)

        try:
            # FIX 6: HQ from same split
            info = i.find_all(class_="companyCardWrapper__interLinking")[0].text.strip().split("|")
            hq.append(info[1].strip())
        except:
            hq.append(np.nan)

    df_1 = pd.DataFrame({
        "name": name,
        "rating": rating,
        "reviews": reviews,
        "company_type": ctype,
        "Head_Quarters": hq
    })

    final = pd.concat([final, df_1], ignore_index=True)

print(final.head())
print(final.shape)

        name rating  reviews              company_type  \
0        TCS    3.3   (1.2L)  IT Services & Consulting
1  Accenture    3.7    (75k)  IT Services & Consulting
2      Wipro    3.6  (66.2k)  IT Services & Consulting
3  Cognizant    3.7  (62.6k)  IT Services & Consulting
4  Capgemini    3.6  (54.6k)  IT Services & Consulting

                    Head_Quarters
0  Bengaluru +448 other locations
1  Bengaluru +261 other locations
2  Hyderabad +375 other locations
3  Hyderabad +233 other locations
4  Bengaluru +188 other locations
(580, 5)

In [353]:
final

,name,rating,reviews,company_type,Head_Quarters
0,TCS,3.3,(1.2L),IT Services & Consulting,Bengaluru +448 other locations
1,Accenture,3.7,(75k),IT Services & Consulting,Bengaluru +261 other locations
2,Wipro,3.6,(66.2k),IT Services & Consulting,Hyderabad +375 other locations
3,Cognizant,3.7,(62.6k),IT Services & Consulting,Hyderabad +233 other locations
4,Capgemini,3.6,(54.6k),IT Services & Consulting,Bengaluru +188 other locations
...,...,...,...,...,...
575,LivSpace,3.3,(1.8k),Architecture & Interior Design,Bengaluru +53 other locations
576,HDFC Securities,3.4,(1.8k),Financial Services,Mumbai +189 other locations
577,XBP Global,3.1,(1.8k),Internet,Chennai +24 other locations
578,Annapurna Finance,3.8,(1.8k),NBFC,Bhubaneswar +411 other locations
579,Kalyan Jewellers,4.4,(1.8k),Jewellery,Thrissur +161 other locations

In [354]:
final.to_csv("companies.csv", index=False)